spring.application.name=Pindura

# Configurações de Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/pindura_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root

#Gui, lembre de substituir a senha do banco aqui
spring.datasource.password=1818813

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
